// src/components/modals/FavoritesModal.vue
<template>
  <Dialog v-model:visible="visible" modal class="favorites-modal" :style="{ width: '480px' }">
    <template #header>
      <div class="favorites-modal__header">
        <i class="pi pi-star"></i>
        <h3>Избранные настройки</h3>
      </div>
    </template>

    <div class="favorites-modal__content">
      <div v-if="!favorites.length" class="favorites-modal__empty">
        <i class="pi pi-star"></i>
        <p>Нет сохраненных конфигураций</p>
        <small>Сохраните фильтры или полигон, чтобы они появились здесь</small>
      </div>

      <div v-else class="favorites-modal__list">
        <div v-for="fav in favorites" :key="fav.id" class="favorite-card">
          <div class="favorite-card__header">
            <div v-if="editingId === fav.id" class="favorite-card__edit">
              <InputText v-model="editingName" class="favorite-card__input" />
              <Button icon="pi pi-check" text rounded @click="saveName(fav)" />
            </div>
            <div v-else class="favorite-card__title">
              <span>{{ fav.name }}</span>
              <Button icon="pi pi-pencil" text rounded @click="startEdit(fav)" />
            </div>
            <Button
              icon="pi pi-trash"
              text
              rounded
              severity="danger"
              @click="emit('delete', fav)"
            />
          </div>

          <div class="favorite-card__tags">
            <Tag v-if="hasPolygon(fav)" severity="secondary">Полигон</Tag>
            <Tag v-if="hasFilters(fav)" severity="secondary">Фильтры</Tag>
          </div>

          <Button
            label="Применить"
            outlined
            size="small"
            class="favorite-card__apply"
            @click="emit('select', fav)"
          />
        </div>
      </div>
    </div>
  </Dialog>
</template>

<script setup>
import { computed, ref } from 'vue';
import Dialog from 'primevue/dialog';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Tag from 'primevue/tag';

const props = defineProps({
  open: {
    type: Boolean,
    default: false,
  },
  favorites: {
    type: Array,
    default: () => [],
  },
});

const emit = defineEmits(['close', 'select', 'delete', 'rename']);

const visible = computed({
  get: () => props.open,
  set: (value) => {
    if (!value) emit('close');
  },
});

const editingId = ref(null);
const editingName = ref('');

function startEdit(fav) {
  editingId.value = fav.id;
  editingName.value = fav.name;
}

function saveName(fav) {
  emit('rename', { ...fav, name: editingName.value });
  editingId.value = null;
}

function hasPolygon(fav) {
  return Array.isArray(fav.geoPoints) && fav.geoPoints.length > 2;
}

function hasFilters(fav) {
  return !!fav.filters && Object.values(fav.filters).some((value) => value);
}
</script>

<style scoped>
.favorites-modal__header {
  display: flex;
  align-items: center;
  gap: 8px;
}

.favorites-modal__header h3 {
  margin: 0;
}

.favorites-modal__content {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.favorites-modal__empty {
  text-align: center;
  color: var(--app-muted-foreground);
  padding: 32px 12px;
}

.favorites-modal__empty i {
  font-size: 2rem;
  opacity: 0.3;
}

.favorites-modal__list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.favorite-card {
  border: 1px solid var(--app-border);
  border-radius: 14px;
  padding: 12px;
}

.favorite-card__header {
  display: flex;
  justify-content: space-between;
  gap: 8px;
  align-items: center;
}

.favorite-card__title {
  display: flex;
  align-items: center;
  gap: 6px;
  font-weight: 600;
}

.favorite-card__edit {
  display: flex;
  align-items: center;
  gap: 6px;
  flex: 1;
}

.favorite-card__input {
  flex: 1;
}

.favorite-card__tags {
  display: flex;
  gap: 6px;
  margin: 8px 0;
}

.favorite-card__apply {
  width: 100%;
}
</style>

// reference-project/src/components/modals/FavoritesModal.jsx
import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Star, Trash2, MapPin, Filter as FilterIcon, Pencil, Check } from 'lucide-react';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';

export default function FavoritesModal({ open, onClose, favorites, onSelect, onDelete, onRename }) {
  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="text-xl font-bold flex items-center gap-2">
            <Star className="w-5 h-5 text-primary fill-primary" />
            Избранные настройки
          </DialogTitle>
        </DialogHeader>

        <ScrollArea className="max-h-[55vh]">
          {favorites.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <Star className="w-10 h-10 mx-auto mb-3 opacity-30" />
              <p>Нет сохранённых конфигураций</p>
              <p className="text-xs mt-1">Сохраните фильтры или полигон, чтобы они появились здесь</p>
            </div>
          ) : (
            <div className="space-y-2 pr-2">
              {favorites.map(fav => (
                <FavoriteCard
                  key={fav.id}
                  fav={fav}
                  onSelect={() => { onSelect(fav); onClose(); }}
                  onDelete={() => onDelete(fav.id)}
                  onRename={(name) => onRename(fav.id, name)}
                />
              ))}
            </div>
          )}
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}

function FavoriteCard({ fav, onSelect, onDelete, onRename }) {
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(fav.name);

  const hasPolygon = fav.geo_points && fav.geo_points.length > 0;
  const hasFilters = fav.filters && Object.values(fav.filters).some(v => v && v !== 'all');

  const handleSaveName = () => {
    onRename(name);
    setEditing(false);
  };

  return (
    <div className="border border-border rounded-xl p-3 hover:border-primary/30 transition-colors">
      <div className="flex items-center justify-between mb-2">
        {editing ? (
          <div className="flex items-center gap-1 flex-1 mr-2">
            <Input value={name} onChange={e => setName(e.target.value)} className="h-7 text-sm" autoFocus />
            <Button variant="ghost" size="icon" className="h-7 w-7" onClick={handleSaveName}>
              <Check className="w-3.5 h-3.5" />
            </Button>
          </div>
        ) : (
          <div className="flex items-center gap-2 min-w-0">
            <p className="font-medium text-sm truncate">{fav.name}</p>
            <Button variant="ghost" size="icon" className="h-6 w-6 shrink-0" onClick={() => setEditing(true)}>
              <Pencil className="w-3 h-3" />
            </Button>
          </div>
        )}
        <Button variant="ghost" size="icon" className="h-7 w-7 text-destructive hover:text-destructive shrink-0" onClick={onDelete}>
          <Trash2 className="w-3.5 h-3.5" />
        </Button>
      </div>

      <div className="flex items-center gap-2 mb-2">
        {hasPolygon && <Badge variant="secondary" className="text-[10px]"><MapPin className="w-3 h-3 mr-0.5" />Полигон</Badge>}
        {hasFilters && <Badge variant="secondary" className="text-[10px]"><FilterIcon className="w-3 h-3 mr-0.5" />Фильтры</Badge>}
      </div>

      <Button variant="outline" size="sm" className="w-full text-xs" onClick={onSelect}>
        Применить
      </Button>
    </div>
  );
}
