// reference-project/src/components/modals/AnalogSlider.jsx
import React, { useRef } from 'react';
import { formatPrice, RENOVATIONS, MATERIALS } from '@/lib/demoData';
import { ChevronLeft, ChevronRight, MapPin, Layers, Maximize2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

export default function AnalogSlider({ analogs }) {
  const scrollRef = useRef(null);

  const scroll = (direction) => {
    if (scrollRef.current) {
      scrollRef.current.scrollBy({ left: direction * 260, behavior: 'smooth' });
    }
  };

  if (!analogs || analogs.length === 0) return null;

  return (
    <div className="mt-4">
      <div className="flex items-center justify-between mb-3">
        <h4 className="font-semibold text-sm text-foreground">Аналоги ({analogs.length})</h4>
        <div className="flex gap-1">
          <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => scroll(-1)}>
            <ChevronLeft className="w-4 h-4" />
          </Button>
          <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => scroll(1)}>
            <ChevronRight className="w-4 h-4" />
          </Button>
        </div>
      </div>

      <div
        ref={scrollRef}
        className="flex gap-3 overflow-x-auto pb-2 scrollbar-hide"
        style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}
      >
        {analogs.map((flat, idx) => (
          <div
            key={flat.id || idx}
            className="min-w-[240px] max-w-[240px] border border-border rounded-xl p-3 bg-muted/30 hover:bg-muted/60 transition-colors shrink-0"
          >
            <div className="flex justify-between items-start mb-2">
              <p className="font-semibold text-sm">{flat.rooms}-комн. · {flat.area} м²</p>
              {flat.similarity && (
                <Badge className="text-[10px] bg-primary/10 text-primary border-0">
                  {Math.round(flat.similarity * 100)}%
                </Badge>
              )}
            </div>
            <p className="text-xs text-muted-foreground flex items-center gap-1 mb-2">
              <MapPin className="w-3 h-3 shrink-0" />
              <span className="truncate">{flat.address}</span>
            </p>
            <div className="flex items-center gap-2 text-xs text-muted-foreground mb-2">
              <span className="flex items-center gap-0.5"><Layers className="w-3 h-3" />{flat.floor}/{flat.total_floors}</span>
              <span>·</span>
              <span>{MATERIALS[flat.material] || flat.material}</span>
            </div>
            <p className="font-bold text-primary text-sm">{formatPrice(flat.price)}</p>
            <p className="text-[11px] text-muted-foreground">
              {new Intl.NumberFormat('ru-RU').format(flat.price_per_sqm)} ₽/м²
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

// src/components/modals/AnalogSlider.vue
<template>
  <div v-if="analogs.length" class="analog-slider">
    <div class="analog-slider__header">
      <h4>Аналоги ({{ analogs.length }})</h4>
      <div class="analog-slider__buttons">
        <Button icon="pi pi-angle-left" text rounded @click="scroll(-1)" />
        <Button icon="pi pi-angle-right" text rounded @click="scroll(1)" />
      </div>
    </div>

    <div ref="scrollRef" class="analog-slider__list">
      <div v-for="analog in analogs" :key="analog.id" class="analog-card">
        <div class="analog-card__header">
          <p>{{ analog.rooms }}-комн. · {{ analog.area }} м²</p>
          <Tag v-if="analog.similarity" severity="secondary">
            {{ Math.round(analog.similarity * 100) }}%
          </Tag>
        </div>
        <p class="analog-card__address">
          <i class="pi pi-map-marker"></i>
          {{ analog.address || 'Без адреса' }}
        </p>
        <p class="analog-card__meta">
          <span>Этаж {{ analog.floor }}</span>
          <span v-if="analog.pricePerSqm">• {{ analog.pricePerSqm }}</span>
        </p>
        <p class="analog-card__price">{{ formatCompactPrice(analog.price) }}</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import Button from 'primevue/button';
import Tag from 'primevue/tag';
import { formatCompactPrice } from '@/utils/formatters';

defineProps({
  analogs: {
    type: Array,
    default: () => [],
  },
});

const scrollRef = ref(null);

function scroll(direction) {
  if (!scrollRef.value) return;
  scrollRef.value.scrollBy({ left: direction * 260, behavior: 'smooth' });
}
</script>

<style scoped>
.analog-slider {
  margin-top: 16px;
}

.analog-slider__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.analog-slider__header h4 {
  margin: 0;
  font-size: 0.85rem;
}

.analog-slider__buttons {
  display: flex;
  gap: 6px;
}

.analog-slider__list {
  display: flex;
  gap: 12px;
  overflow-x: auto;
  padding-bottom: 8px;
  margin-top: 10px;
}

.analog-card {
  min-width: 220px;
  max-width: 220px;
  border: 1px solid var(--app-border);
  border-radius: 14px;
  padding: 12px;
  background: rgba(242, 236, 230, 0.4);
}

.analog-card__header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 6px;
}

.analog-card__header p {
  margin: 0;
  font-weight: 600;
  font-size: 0.8rem;
}

.analog-card__address {
  margin: 6px 0 0;
  font-size: 0.7rem;
  color: var(--app-muted-foreground);
  display: flex;
  gap: 4px;
  align-items: center;
}

.analog-card__meta {
  margin: 6px 0 0;
  font-size: 0.7rem;
  color: var(--app-muted-foreground);
}

.analog-card__price {
  margin: 8px 0 0;
  font-weight: 700;
  color: var(--app-primary);
}
</style>
