// src/components/sidebar/PropertyCard.vue
<template>
  <div
    class="property-card"
    :class="{ 'property-card--selected': isSelected }"
    @click="emit('click')"
  >
    <div class="property-card__header">
      <div>
        <p class="property-card__title">{{ flat.rooms }}-комн. · {{ flat.area }} м²</p>
        <p class="property-card__address">
          <i class="pi pi-map-marker"></i>
          {{ flat.address || 'Без адреса' }}
        </p>
      </div>
      <Tag class="property-card__source" severity="secondary">
        {{ sourceLabel }}
      </Tag>
    </div>

    <div class="property-card__meta">
      <span><i class="pi pi-layers"></i> Этаж {{ flat.floor }}</span>
      <span v-if="flat.pricePerSqmLabel">• {{ flat.pricePerSqmLabel }}</span>
    </div>

    <div class="property-card__footer">
      <div>
        <p class="property-card__price">{{ formatCompactPrice(flat.price) }}</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import Tag from 'primevue/tag';
import { formatCompactPrice } from '@/utils/formatters';

const props = defineProps({
  flat: {
    type: Object,
    required: true,
  },
  isSelected: {
    type: Boolean,
    default: false,
  },
});

const emit = defineEmits(['click']);

const sourceLabel = computed(() => {
  const map = {
    cian: 'Циан',
    domclick: 'Домклик',
    avito: 'Авито',
  };
  return map[props.flat.source] || props.flat.source || 'Источник';
});
</script>

<style scoped>
.property-card {
  padding: 14px;
  border-radius: 16px;
  background: var(--app-card);
  border: 1px solid var(--app-border);
  cursor: pointer;
  transition:
    border 0.2s ease,
    box-shadow 0.2s ease,
    transform 0.2s ease;
}

.property-card:hover {
  border-color: rgba(255, 0, 30, 0.4);
  box-shadow: 0 6px 18px rgba(15, 23, 42, 0.08);
  transform: translateY(-1px);
}

.property-card--selected {
  border-color: var(--app-primary);
  background: var(--app-accent);
}

.property-card__header {
  display: flex;
  justify-content: space-between;
  gap: 12px;
}

.property-card__title {
  margin: 0;
  font-weight: 600;
  font-size: 0.95rem;
}

.property-card__address {
  margin: 4px 0 0;
  font-size: 0.75rem;
  color: var(--app-muted-foreground);
  display: flex;
  gap: 4px;
  align-items: center;
}

.property-card__source {
  font-size: 0.65rem;
  padding: 2px 6px;
}

.property-card__meta {
  margin-top: 8px;
  font-size: 0.75rem;
  color: var(--app-muted-foreground);
  display: flex;
  gap: 8px;
  align-items: center;
}

.property-card__footer {
  margin-top: 10px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.property-card__price {
  margin: 0;
  font-weight: 700;
  color: var(--app-primary);
}
</style>

// reference-project/src/components/sidebar/PropertyCard.jsx
import React from 'react';
import { Badge } from '@/components/ui/badge';
import { formatPrice, RENOVATIONS, SOURCES } from '@/lib/demoData';
import { MapPin, Maximize2, Layers } from 'lucide-react';

export default function PropertyCard({ flat, isSelected, onClick }) {
  return (
    <div
      onClick={onClick}
      className={`p-4 rounded-xl cursor-pointer transition-all duration-200 border ${
        isSelected
          ? 'border-primary bg-accent shadow-md'
          : 'border-border bg-card hover:border-primary/40 hover:shadow-sm'
      }`}
    >
      <div className="flex justify-between items-start mb-2">
        <div>
          <p className="font-semibold text-base text-foreground">
            {flat.rooms}-комн. · {flat.area} м²
          </p>
          <p className="text-xs text-muted-foreground flex items-center gap-1 mt-0.5">
            <MapPin className="w-3 h-3" />
            {flat.address}
          </p>
        </div>
        <Badge variant="secondary" className="text-xs shrink-0">
          {SOURCES[flat.source] || flat.source}
        </Badge>
      </div>

      <div className="flex items-center gap-3 text-xs text-muted-foreground mb-2">
        <span className="flex items-center gap-1">
          <Layers className="w-3 h-3" />
          {flat.floor}/{flat.total_floors} эт.
        </span>
        <span className="flex items-center gap-1">
          <Maximize2 className="w-3 h-3" />
          Кухня {flat.kitchen_area} м²
        </span>
      </div>

      <div className="flex justify-between items-end">
        <div>
          <p className="text-lg font-bold text-primary">{formatPrice(flat.price)}</p>
          <p className="text-xs text-muted-foreground">
            {new Intl.NumberFormat('ru-RU').format(flat.price_per_sqm)} ₽/м²
          </p>
        </div>
        {flat.renovation && flat.renovation !== 'none' && (
          <Badge variant="outline" className="text-xs">
            {RENOVATIONS[flat.renovation]}
          </Badge>
        )}
      </div>
    </div>
  );
}
