// src/components/toolbar/LeftNavPanel.vue
<template>
  <aside class="left-nav">
    <div class="left-nav__header">
      <div class="left-nav__brand">
        <div class="left-nav__logo">
          <i class="pi pi-building"></i>
        </div>
        <div>
          <h1 class="left-nav__title">Оценка квартир</h1>
          <p class="left-nav__subtitle">
            <i class="pi pi-map-marker"></i>
            {{ selectedCity?.label || 'Город' }}
          </p>
        </div>
      </div>
      <div class="left-nav__count">{{ totalFlats }} объектов на карте</div>
      <Select
        v-if="cityOptions.length > 1"
        :model-value="selectedCity"
        :options="cityOptions"
        option-label="label"
        class="left-nav__city"
        @update:model-value="handleCityChange"
      />
    </div>

    <nav class="left-nav__items">
      <button class="left-nav__item" @click="emit('valuation')">
        <i class="pi pi-calculator"></i>
        <div>
          <span>Оценка стоимости</span>
          <small>Прогноз цены по параметрам</small>
        </div>
      </button>

      <button
        class="left-nav__item"
        :class="{ 'left-nav__item--active': hasActiveFilters }"
        @click="emit('filters')"
      >
        <i class="pi pi-filter"></i>
        <div>
          <span>Фильтры</span>
          <small>Поиск квартир на карте</small>
        </div>
        <span v-if="hasActiveFilters" class="left-nav__badge">Активны</span>
      </button>

      <div class="left-nav__heatmap">
        <button
          class="left-nav__item"
          :class="{ 'left-nav__item--active': !!heatMode }"
          @click="toggleHeatmapMenu"
        >
          <i class="pi pi-fire"></i>
          <div>
            <span>Тепловая карта</span>
            <small>{{ heatModeLabel || 'Выберите параметр' }}</small>
          </div>
          <i
            v-if="!heatMode"
            class="pi pi-chevron-right left-nav__chevron"
            :class="{ rotated: showHeatmapMenu }"
          ></i>
        </button>

        <div v-if="showHeatmapMenu && !heatMode" class="left-nav__submenu">
          <button v-for="mode in heatmapOptions" :key="mode.id" @click="selectHeatMode(mode.id)">
            {{ mode.label }}
          </button>
        </div>
      </div>
    </nav>

    <footer class="left-nav__footer">ООО Брусника · 2026</footer>
  </aside>
</template>

<script setup>
import { computed, ref } from 'vue';
import Select from 'primevue/select';

const props = defineProps({
  totalFlats: {
    type: Number,
    default: 0,
  },
  hasActiveFilters: {
    type: Boolean,
    default: false,
  },
  heatMode: {
    type: String,
    default: null,
  },
  heatmapOptions: {
    type: Array,
    default: () => [],
  },
  selectedCity: {
    type: Object,
    default: null,
  },
  cityOptions: {
    type: Array,
    default: () => [],
  },
});

const emit = defineEmits(['valuation', 'filters', 'heatmap', 'city-change']);

const showHeatmapMenu = ref(false);

const heatModeLabel = computed(
  () => props.heatmapOptions.find((mode) => mode.id === props.heatMode)?.label
);

function toggleHeatmapMenu() {
  if (props.heatMode) {
    emit('heatmap', null);
    showHeatmapMenu.value = false;
    return;
  }
  showHeatmapMenu.value = !showHeatmapMenu.value;
}

function selectHeatMode(mode) {
  emit('heatmap', mode);
  showHeatmapMenu.value = false;
}

function handleCityChange(city) {
  emit('city-change', city);
}
</script>

<style scoped>
.left-nav {
  width: 220px;
  background: rgba(255, 255, 255, 0.95);
  border-right: 1px solid var(--app-border);
  box-shadow: var(--app-shadow);
  display: flex;
  flex-direction: column;
  z-index: 5;
}

.left-nav__header {
  padding: 20px 18px 16px;
  border-bottom: 1px solid var(--app-border);
}

.left-nav__brand {
  display: flex;
  gap: 12px;
  align-items: center;
}

.left-nav__logo {
  width: 36px;
  height: 36px;
  border-radius: 12px;
  background: var(--app-primary);
  color: var(--app-primary-contrast);
  display: grid;
  place-items: center;
}

.left-nav__title {
  font-size: 0.9rem;
  margin: 0;
  font-weight: 700;
}

.left-nav__subtitle {
  margin: 4px 0 0;
  font-size: 0.7rem;
  color: var(--app-muted-foreground);
  display: flex;
  gap: 4px;
  align-items: center;
}

.left-nav__count {
  margin-top: 12px;
  background: var(--app-muted);
  border-radius: 10px;
  padding: 6px 8px;
  font-size: 0.75rem;
  text-align: center;
  font-weight: 600;
}

.left-nav__city {
  width: 100%;
  margin-top: 10px;
}

.left-nav__items {
  flex: 1;
  padding: 14px 12px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.left-nav__item {
  width: 100%;
  border: none;
  background: transparent;
  padding: 12px;
  border-radius: 14px;
  display: flex;
  gap: 10px;
  align-items: flex-start;
  text-align: left;
  cursor: pointer;
  transition:
    background 0.2s ease,
    color 0.2s ease;
  color: var(--app-foreground);
}

.left-nav__item i {
  color: var(--app-primary);
  font-size: 0.95rem;
  margin-top: 2px;
}

.left-nav__item span {
  display: block;
  font-weight: 600;
  font-size: 0.85rem;
}

.left-nav__item small {
  display: block;
  font-size: 0.7rem;
  color: var(--app-muted-foreground);
  margin-top: 2px;
}

.left-nav__item:hover {
  background: var(--app-muted);
}

.left-nav__item--active {
  background: var(--app-primary);
  color: var(--app-primary-contrast);
}

.left-nav__item--active:hover {
  background: var(--app-primary);
}

.left-nav__item--active i,
.left-nav__item--active small {
  color: var(--app-primary-contrast);
}

.left-nav__badge {
  margin-left: auto;
  background: rgba(255, 255, 255, 0.2);
  border-radius: 999px;
  padding: 2px 8px;
  font-size: 0.6rem;
  font-weight: 600;
}

.left-nav__heatmap {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.left-nav__submenu {
  margin-left: 12px;
  border: 1px solid var(--app-border);
  border-radius: 12px;
  padding: 6px;
  background: rgba(241, 237, 232, 0.6);
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.left-nav__submenu button {
  border: none;
  background: transparent;
  padding: 6px 10px;
  border-radius: 8px;
  text-align: left;
  cursor: pointer;
}

.left-nav__submenu button:hover {
  background: var(--app-card);
}

.left-nav__chevron {
  margin-left: auto;
  font-size: 0.75rem;
  color: var(--app-muted-foreground);
  transition: transform 0.2s ease;
}

.left-nav__chevron.rotated {
  transform: rotate(90deg);
}

.left-nav__footer {
  padding: 14px 12px;
  text-align: center;
  font-size: 0.65rem;
  color: var(--app-muted-foreground);
  border-top: 1px solid var(--app-border);
}
</style>

// reference-project/src/components/toolbar/LeftNavPanel.jsx
import React, { useState } from 'react';
import { Building2, Calculator, Filter, Flame, MapPin, ChevronRight } from 'lucide-react';
import { Badge } from '@/components/ui/badge';

const HEATMAP_MODES = [
  { id: 'price', label: 'По цене м²' },
  { id: 'count', label: 'По кол-ву объявлений' },
  { id: 'year', label: 'По году постройки' },
  { id: 'metro', label: 'По близости к метро' },
];

export default function LeftNavPanel({
  onValuation,
  onFilters,
  onToggleHeatmap,
  heatMode,
  hasActiveFilters,
  totalFlats,
}) {
  const [showHeatmapMenu, setShowHeatmapMenu] = useState(false);

  const handleHeatmapMode = (mode) => {
    onToggleHeatmap(mode);
    setShowHeatmapMenu(false);
  };

  const handleHeatmapClick = () => {
    if (heatMode) {
      onToggleHeatmap(null);
      setShowHeatmapMenu(false);
    } else {
      setShowHeatmapMenu((v) => !v);
    }
  };

  return (
    <div className="absolute top-0 left-0 h-full w-[220px] z-10 bg-card/95 backdrop-blur-md border-r border-border shadow-xl flex flex-col">
      {/* Logo */}
      <div className="px-5 py-5 border-b border-border">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 bg-primary rounded-xl flex items-center justify-center shrink-0">
            <Building2 className="w-5 h-5 text-primary-foreground" />
          </div>
          <div>
            <h1 className="font-bold text-sm text-foreground leading-tight">Оценка квартир</h1>
            <p className="text-[11px] text-muted-foreground flex items-center gap-1 mt-0.5">
              <MapPin className="w-3 h-3" />
              Екатеринбург
            </p>
          </div>
        </div>
        <div className="mt-3">
          <Badge variant="secondary" className="text-xs font-medium w-full justify-center py-1">
            {totalFlats} объектов на карте
          </Badge>
        </div>
      </div>

      {/* Nav items */}
      <nav className="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
        <NavItem
          icon={<Calculator className="w-4 h-4" />}
          label="Оценка стоимости"
          description="Прогноз цены по параметрам"
          onClick={onValuation}
        />
        <NavItem
          icon={<Filter className="w-4 h-4" />}
          label="Фильтры"
          description="Поиск квартир на карте"
          onClick={onFilters}
          active={hasActiveFilters}
          badge={hasActiveFilters ? 'Активны' : null}
        />

        {/* Heatmap with submenu */}
        <div>
          <button
            onClick={handleHeatmapClick}
            className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-150 text-left group ${
              heatMode
                ? 'bg-primary text-primary-foreground shadow-sm'
                : 'hover:bg-muted text-foreground'
            }`}
          >
            <div className={`shrink-0 ${heatMode ? 'text-primary-foreground' : 'text-primary'}`}>
              <Flame className="w-4 h-4" />
            </div>
            <div className="min-w-0 flex-1">
              <div className="flex items-center justify-between gap-1">
                <span className="text-sm font-medium truncate">Тепловая карта</span>
                {!heatMode && (
                  <ChevronRight
                    className={`w-3 h-3 text-muted-foreground transition-transform ${showHeatmapMenu ? 'rotate-90' : ''}`}
                  />
                )}
              </div>
              <p
                className={`text-[11px] truncate mt-0.5 ${heatMode ? 'text-primary-foreground/70' : 'text-muted-foreground'}`}
              >
                {heatMode
                  ? HEATMAP_MODES.find((m) => m.id === heatMode)?.label
                  : 'Выберите параметр'}
              </p>
            </div>
          </button>

          {showHeatmapMenu && !heatMode && (
            <div className="mt-1 ml-2 space-y-0.5 bg-muted/50 rounded-xl p-1.5 border border-border">
              {HEATMAP_MODES.map((mode) => (
                <button
                  key={mode.id}
                  onClick={() => handleHeatmapMode(mode.id)}
                  className="w-full text-left px-3 py-2 rounded-lg text-sm hover:bg-card transition-colors text-foreground"
                >
                  {mode.label}
                </button>
              ))}
            </div>
          )}
        </div>
      </nav>

      {/* Footer */}
      <div className="px-4 py-4 border-t border-border">
        <p className="text-[10px] text-muted-foreground text-center">ООО Брусника · 2026</p>
      </div>
    </div>
  );
}

function NavItem({ icon, label, description, onClick, active, badge }) {
  return (
    <button
      onClick={onClick}
      className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-150 text-left group ${
        active ? 'bg-primary text-primary-foreground shadow-sm' : 'hover:bg-muted text-foreground'
      }`}
    >
      <div className={`shrink-0 ${active ? 'text-primary-foreground' : 'text-primary'}`}>
        {icon}
      </div>
      <div className="min-w-0 flex-1">
        <div className="flex items-center justify-between gap-1">
          <span className="text-sm font-medium truncate">{label}</span>
          {badge && (
            <span className="text-[10px] bg-primary-foreground/20 rounded-full px-1.5 py-0.5 font-medium shrink-0">
              {badge}
            </span>
          )}
        </div>
        <p
          className={`text-[11px] truncate mt-0.5 ${active ? 'text-primary-foreground/70' : 'text-muted-foreground'}`}
        >
          {description}
        </p>
      </div>
    </button>
  );
}
